# Generated by Django 4.0 on 2022-02-06 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_position_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='user',
        ),
    ]
