# Generated by Django 4.0 on 2022-02-07 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_user_is_logged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pos', to='mainapp.position'),
        ),
    ]
