# Generated by Django 4.0 on 2022-02-07 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_user_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='in_charge', to='mainapp.user'),
        ),
    ]
