# Generated by Django 4.0 on 2022-02-07 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_department_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_in_charge',
            field=models.BooleanField(default=False),
        ),
    ]
