# Generated by Django 4.0 on 2022-02-07 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_user_is_in_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='in_charge_of',
            field=models.ManyToManyField(blank=True, related_name='departments_headed', to='mainapp.Department'),
        ),
        migrations.AlterField(
            model_name='user',
            name='designation',
            field=models.ManyToManyField(blank=True, related_name='departments_assigned', to='mainapp.Department'),
        ),
    ]
