# Generated by Django 4.0.2 on 2022-02-17 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_user_in_charge_of_alter_user_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='facebook',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_number',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='tel_number',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
