# Generated by Django 4.0.2 on 2022-02-17 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_alter_user_mobile_number_alter_user_tel_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='mobile_number',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='tel_number',
            new_name='telephone',
        ),
    ]
