# Generated by Django 4.0.2 on 2022-02-21 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_rename_mobile_number_user_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='in_charge', to=settings.AUTH_USER_MODEL),
        ),
    ]
