# Generated by Django 4.0.2 on 2022-03-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_alter_department_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='level',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='position',
            name='salary_1',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='position',
            name='salary_2',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='position',
            name='salary_3',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='position',
            name='salary_4',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='position',
            name='salary_5',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
