# Generated by Django 4.0.2 on 2022-03-15 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_position_level_position_salary_1_position_salary_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='level',
        ),
    ]
